### ISSUE TITLE
[BUG] Webhook missing positional argiment

### ISSUE THREAD

**Issue by 3vilGremlin** [evilsocket/pwnagotchi#421]
Seeing the following error after upgrade to 1.1.0RC0

pwnagotchi-launcher[436]: [2019-10-27 11:38:12,184] [ERROR] on_webhook() missing 1 required positional argument: 'path'

Have rebooted but issue persists.

Running on RPi0 with WaveShare V2 screen and no other attachments
Plugins installed are:

auto-update
memtemp
bt-tether
net-pos
aircrackonly
wpa-sec
onlinehashcrack
webgpsmap
